briis/unifiprotect

custom_components/unifiprotect/unifi_protect_server.py
All async logic is handled on the HA side, so only 2 small changes needed to get rid of the messages.
=> Adding fixes for Blocking I/O messages in HA 0.109

README.md, custom_components/unifiprotect/__init__.py, custom_components/unifiprotect/binary_sensor.py, custom_components/unifiprotect/camera.py, custom_components/unifiprotect/sensor.py, custom_components/unifiprotect/switch.py, custom_components/unifiprotect/unifi_protect_server.py
This fixes the warning that started in 0.109.0 (see #36 ) and converts the entire component to be async.  
I verified the following with these changes:
* Warning in HA 0.109 goes away.
* My switch/camera/binary sensor/sensors showed up correctly.
* All 3 registered services work.
* The `camera.snapshot` service works.
I apologize for the large diff, I tried a few simple things to get rid of the warning but ran into a lot of issues.  I decided to just go head and make it all async.
There are a lot of formatting changes due to my IDE auto-formatting code using [black](https://black.readthedocs.io/en/stable/) standards (which HA also uses in their code base).
=> Make component async

.devcontainer/configuration.yaml, .devcontainer/devcontainer.json, .gitignore, custom_components/unifiprotect/__init__.py, custom_components/unifiprotect/unifi_protect_server.py
This is a DRAFT PR with a fix for #21 
This works with my UDM Pro without the use of the Proxy, ie the config is:
```
unifiprotect:
host: 192.168.1.1
port: 443
username: !secret unifiprotect_user
password: !secret unifiprotect_password
```
@briis I don't have the a CloudKey any more, could you please test if these changes works against the CouldKey?
=> Direct UnifiOS support

custom_components/unifiprotect/__init__.py, custom_components/unifiprotect/binary_sensor.py, custom_components/unifiprotect/camera.py, custom_components/unifiprotect/config_flow.py, custom_components/unifiprotect/const.py, custom_components/unifiprotect/data.py, custom_components/unifiprotect/entity.py, custom_components/unifiprotect/sensor.py, custom_components/unifiprotect/switch.py
Motion and doorbell updates should now happen
right away
Reduces the amount of entity updates since we
now only update cameras that change when we
poll instead of them all.
Fixes https://github.com/briis/unifiprotect/issues/97
Requires https://github.com/briis/pyunifiprotect/pull/6
Thanks to @hjdhjd for decoding the protocol
=> Add websocket support

custom_components/unifiprotect/__init__.py, custom_components/unifiprotect/binary_sensor.py, custom_components/unifiprotect/camera.py, custom_components/unifiprotect/config_flow.py, custom_components/unifiprotect/const.py, custom_components/unifiprotect/data.py, custom_components/unifiprotect/sensor.py, custom_components/unifiprotect/switch.py
I noticed the listener wasn't being removed when the integration was removed.
Small tweaks
=> Ensure the config entry listner is unsubscribed on unload

custom_components/unifiprotect/translations/en.json
There was a small typo (_allready_ instead of _already_). Went ahead and fixed it ;-)
=> Fixes a typo in the English translation

custom_components/unifiprotect/__init__.py, custom_components/unifiprotect/binary_sensor.py, custom_components/unifiprotect/camera.py, custom_components/unifiprotect/light.py, custom_components/unifiprotect/sensor.py, custom_components/unifiprotect/switch.py
HomeAssistantType was removed in https://github.com/home-assistant/core/pull/49593
=> Fix compat with latest dev

README.md
Just thought this would be useful for folks
=> Added helpful tip for debug logging

README.md
I know this paragraph was probably perfectly clear to HA veterans, but for a noob like me who is still learning my way around, this little bit of clarification would have eliminated some confusion on my part.
=> Clarify Configuration paragraph

custom_components/unifiprotect/__init__.py
=> Ensure setup is retried later when device is rebooting

custom_components/unifiprotect/camera.py
For 2021.9
https://github.com/home-assistant/core/pull/53835
https://github.com/home-assistant/developers.home-assistant/pull/1020
=> Allow requesting a custom snapshot width and height

custom_components/unifiprotect/__init__.py
Changed the write to `hass.data` to after all `ConfigEntryNotReady`
=> Moved/changed hass.data write

.gitignore, custom_components/unifiprotect/binary_sensor.py, custom_components/unifiprotect/camera.py, custom_components/unifiprotect/entity.py, custom_components/unifiprotect/light.py, custom_components/unifiprotect/number.py, custom_components/unifiprotect/select.py, custom_components/unifiprotect/sensor.py, custom_components/unifiprotect/switch.py
All entities now using `extra_state_attributes` and all comments in these files have been removed.
=> Migrated to extra_state_attributes

.devcontainer/Dockerfile, .devcontainer/configuration.yaml, .devcontainer/devcontainer.json, .vscode/launch.json, .vscode/tasks.json
* Adds Dockerfile to help install extra requirements
* Adds debugpy to configration.yaml
* Changes HA port to 9123 so there is no port remapping
* Adds persistent volume for HA config
* Adds tasks.json to help discover how to run HA
* Adds comment on how to debug HA
=> Updates dev env

custom_components/unifiprotect/select.py
First round of select cleanups
=> Select cleanup

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .vscode/tasks.json, custom_components/unifiprotect/strings.json, custom_components/unifiprotect/translations/en.json
* Adds hass to workspaces
* Adds task to update translations
* Renames VSC Workspace name to make it shorter.
* Fixes `strings.json` and regenerated translations
=> Adds hass to workspaces. Adds task to update translations

README.md
I've noticed that the link to the doorbell notification in the table of contents wasn't working. 
* Fixed Table of Contents link in README.md
* Fixed some typo's and interpuntion in README.md
=> Fix Table of Contents and some typo's in README.md

custom_components/unifiprotect/binary_sensor.py
Picture speaks plenty here. Lol.
=> Fixes detected object

CHANGELOG.md, custom_components/unifiprotect/sensor.py, custom_components/unifiprotect/views.py
* Fixes issue in `ThumbnailProxyView` from last refactor PR that was missed from linting
* `NEW`: Added Detected Object sensor for cameras with smart detections. Values are `none`, `person` or `vehicle`. Contains `event_score` and `event_thumb` attributes.
* Closes #342
=> Adds Detected Object sensor

custom_components/unifiprotect/binary_sensor.py
=> Fixes error for motion events for UFP-Sense

blueprints/automation/unifiprotect/push_notification_doorbell_event.yaml, blueprints/automation/unifiprotect/push_notification_motion_event.yaml, blueprints/automation/unifiprotect/push_notification_smart_event.yaml
Since I got TTS messages 100% fixed for 0.11.1, here are TTS messages for the Doorbell notification blueprint.
=> Adds TTS for doorbell notification

custom_components/unifiprotect/button.py, custom_components/unifiprotect/camera.py, custom_components/unifiprotect/data.py, custom_components/unifiprotect/entity.py, custom_components/unifiprotect/light.py, custom_components/unifiprotect/number.py, custom_components/unifiprotect/select.py, custom_components/unifiprotect/switch.py
More backports from latest PRs. Again, no code changes.
=> More core backports

custom_components/unifiprotect/binary_sensor.py, custom_components/unifiprotect/const.py, custom_components/unifiprotect/manifest.json
Depends un-released pyunifiprotect code
=> Use is_ringing attr for pyunifiprotect

custom_components/unifiprotect/binary_sensor.py, custom_components/unifiprotect/camera.py, custom_components/unifiprotect/sensor.py
* Fixes memory sensor if no data is reported
* Fixes https://github.com/briis/unifiprotect/issues/440
* Fixes is connected check for cameras
* Adds last_trip_time back to camera motion entity
=> Batch of small bugfixes

custom_components/unifiprotect/binary_sensor.py, custom_components/unifiprotect/camera.py, custom_components/unifiprotect/data.py, custom_components/unifiprotect/entity.py, custom_components/unifiprotect/manifest.json, custom_components/unifiprotect/models.py, custom_components/unifiprotect/number.py, custom_components/unifiprotect/select.py, custom_components/unifiprotect/sensor.py, custom_components/unifiprotect/switch.py
Backports the following 3 new PRs from core:
* https://github.com/home-assistant/core/pull/64019
* https://github.com/home-assistant/core/pull/63993
* https://github.com/home-assistant/core/pull/63985
* https://github.com/home-assistant/core/pull/64145
Also includes the version bump that will include the new Websocket code (https://github.com/briis/pyunifiprotect/pull/161).
=> Backports from Core
