briis/unifiprotect

.devcontainer/configuration.yaml, .devcontainer/devcontainer.json, custom_components/unifiprotect/unifi_protect_server.py
Contains a fix for the issue I mentioned in #21 to handle that the authentication token has expired, in which case it will automatically authenticate again. Please test if everything still works on CloudKey+
Btw I also added .devcontainer back from my last PR. You may not be familiar with this feature but it makes it very easy to get a separate python dev environment and a separate instance of home assistance running docker for development in Visual Studio Code.
I am using it for all my small HA contributions. It is a cool technology and very easy to use.
More info here: https://code.visualstudio.com/docs/remote/containers
Basically just install docker on you dev machine and use Visual Studio Code and the VSCode extension. And btw the Home Assistant repo itself also has a .devcontainer …
=> Handle authentication token expiration for UnifiOS

.devcontainer/configuration.yaml, .devcontainer/devcontainer.json, .vscode/launch.json
Hi Bjarne,
Just a small PR to improve the .devcontainer setup so that the debugger in VS Code works to debug the integration.
Also note that when you use create the devcontainer it pulls the latests version of the Home Assistant dev branch. And I get some error right now during init as the dev branch seems to some error currently.
In the VS code shell you can type "container set-version" to chose which Home Assistant version is used e.g. 0.109.4
Also if you type just "container" it will list the commands available.
=> DevContainer: Enable debugger 

custom_components/unifiprotect/unifi_protect_server.py
Use camera.get("lastRing") instead of camera["lastRing"] to work around cases where the camera object does not have a "lastRing" member. get() will return None if "lastRing" is not present.
This resolves https://github.com/briis/unifiprotect/issues/54
=> Fix missing lastRing data with get()

custom_components/unifiprotect/data.py, custom_components/unifiprotect/switch.py
Force a camera update when changing the switch so it updates right away.
Disconnect websocket when the integration is unloaded.
Requires https://github.com/briis/pyunifiprotect/pull/7
=> Force a camera update when changing the switch

custom_components/unifiprotect/__init__.py
We would continue on if the first bootstrap call failed which could lead to partial setup. Usually the 500 error is transient so throwing `ConfigEntryNotReady` will cause the config entry to try again later.
Fixes #181
=> Add a retry if the first update request fails

custom_components/unifiprotect/__init__.py, custom_components/unifiprotect/config_flow.py
The unique id needs to be stable.  Since the name can change, we should use the device_id since it never will
needs https://github.com/briis/pyunifiprotect/pull/22
=> Use the server id for the unique id

custom_components/unifiprotect/__init__.py
Fixes error when auth failes `2021-04-09 03:16:36 ERROR (MainThread) [homeassistant.config_entries] unifiprotect.async_setup_entry did not return boolean`
=> Return False when auth fails

custom_components/unifiprotect/__init__.py, custom_components/unifiprotect/config_flow.py, custom_components/unifiprotect/data.py, custom_components/unifiprotect/manifest.json, custom_components/unifiprotect/strings.json, custom_components/unifiprotect/translations/da.json, custom_components/unifiprotect/translations/de.json, custom_components/unifiprotect/translations/en.json, custom_components/unifiprotect/translations/fr.json, custom_components/unifiprotect/translations/nb.json, custom_components/unifiprotect/translations/nl.json
I ran through your suggestions Nick, and have modified `config_flow.py` and `__init__.py` according to your suggestions. It does work, but I am getting an error when I run the STOP command from the Server Management page, and I am not sure why that happens. Here is the log:
```log
2021-11-08 07:06:53 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback UnifiProtectData.async_stop(<Event homeassistant_stop[L]>)
Traceback (most recent call last):
File "/usr/local/python/lib/python3.9/asyncio/events.py", line 80, in _run
self._context.run(self._callback, *self._args)
File "/usr/local/python/lib/python3.9/site-packages/homeassistant/core.py", line 835, in _onetime_listener
self._hass.async_run_job(listener, event)
File …
```
=> Fixing Standard Issue

.devcontainer/configuration.yaml, .vscode/tasks.json, custom_components/unifiprotect/camera.py
* Tweaks dev configuration a bit more
* Adds VS Code task to easily install dev version of HA
* Fixes HLS streaming for camera entities
While I was testing stuff for @bdraco, I noticed that I could no longer do streaming with my UFP cameras. After digging into it, it looks like [this refactor](https://github.com/briis/unifiprotect/pull/336/files#diff-c33d3ccf9e61ed4e354cb42e481a9a258c38eb924658d6abe44f8ae0d3432a7cL152-L162) was the cause.
Core uses the [frontend_stream_type](https://github.com/home-assistant/core/blob/dev/homeassistant/components/camera/__init__.py#L423) attribute, which in turn uses the `supported_features` attribute to enable HLS.
=> Fixes HLS streaming

custom_components/unifiprotect/translations/da.json, custom_components/unifiprotect/translations/de.json, custom_components/unifiprotect/translations/en.json, custom_components/unifiprotect/translations/fr.json, custom_components/unifiprotect/translations/nb.json, custom_components/unifiprotect/translations/nl.json
Since UnifiOS is required now, remove references about UnifiOS/Non-UniFiOS devices in port configuration.
=> Removes references to UnifiOS port configuration

.devcontainer/Dockerfile, .vscode/tasks.json
The helper script provided by the base container is "dumb" and cannot handle multiple folders in workspaces. 
* Moves `hass` folder to `/opt` (that is where the other container provided scripts are)
=> Fixes home assistant path

custom_components/unifiprotect/__init__.py, custom_components/unifiprotect/config_flow.py, custom_components/unifiprotect/data.py, custom_components/unifiprotect/strings.json, custom_components/unifiprotect/translations/da.json, custom_components/unifiprotect/translations/de.json, custom_components/unifiprotect/translations/en.json, custom_components/unifiprotect/translations/fr.json, custom_components/unifiprotect/translations/nb.json, custom_components/unifiprotect/translations/nl.json
* Raise `ConfigEntryAuthFailed` on auth failure
* Adds `async_step_reauth` to allow reauth on auth failure
* Refactors `async_step_user` to allow it to be shared between user and reauth steps.
* Updates strings to fix casing of "UniFi"
* Simplifies options flow to only have Disable RTSP and Doorbell Texts
=> Refactors config flow and adds reauth

custom_components/unifiprotect/switch.py
Temporarily disables High FPS mode switch. We are not doing the proper checks on 0.10 to verify the camera _has_ a High FPS mode before adding the switch. Cameras that do not have one (G3 Flex, G3 Instance, G3 Bullet and G4 Instant) will become bricked and it is quite difficult to fix the issue.
Temporarily fix for https://github.com/briis/unifiprotect/issues/358 until we get 0.11 done.
The PR I have for 0.11 has this issue fixed already as I am using `feature_flags.video_modes` to determine if the camera has a High FPS mode.
Image of High FPS mode switch existing on my G4 Instant: 
But as you can see, it does not have a high FPS video mode.
=> Disables High FPS switch

CHANGELOG.md, custom_components/unifiprotect/number.py, custom_components/unifiprotect/services.py, custom_components/unifiprotect/utils.py
* Allows `device_id` for service calls to be any device from the UFP instance.
* Fixes issues with number entity from previous merge
=> Improves service calls

.vscode/launch.json, custom_components/unifiprotect/__init__.py, custom_components/unifiprotect/binary_sensor.py, custom_components/unifiprotect/button.py, custom_components/unifiprotect/camera.py, custom_components/unifiprotect/config_flow.py, custom_components/unifiprotect/const.py, custom_components/unifiprotect/data.py, custom_components/unifiprotect/entity.py, custom_components/unifiprotect/light.py, custom_components/unifiprotect/manifest.json, custom_components/unifiprotect/media_player.py, custom_components/unifiprotect/models.py, custom_components/unifiprotect/number.py, custom_components/unifiprotect/select.py, custom_components/unifiprotect/sensor.py, custom_components/unifiprotect/services.py, custom_components/unifiprotect/switch.py
Based on feedback from a PR I made to update the UniFi Network integration for HA and looking at other stuff. I renamed all instances of "Unifi" to "UniFi" in the code. This makes our code align more with Ubiquiti's brand.
For classes and such, I just removed "Unifi" all together. So `UnifiProtectData` becomes `ProtectData`. This both makes it easier to stay in-line with Ubiquiti's brand and shortens the classes for a number of classes we have in the code.
=> Replaces all instances of Unifi

custom_components/unifiprotect/binary_sensor.py, custom_components/unifiprotect/manifest.json
* Bumps version of pyunifiprotect to 1.2.3 to get retry logic for thumbnails
* Fixes IndexError for access tokens
* Fixes ValueError if doorbell has never rang
=> Bugfixes from 0.11-beta2

custom_components/unifiprotect/__init__.py, custom_components/unifiprotect/const.py, custom_components/unifiprotect/utils.py
* Removes some unused const variables
* Refactored service setup so the services will only be loaded once (multiple entries will not try to load more) and so they will be removed when all entries are unloaded
I did look into the view, it is kind of wasteful to register it multiple times, but it should be harmless for it to be registered multiple times or be registered when no entries are loaded. 
URL routers (from my experience) use the first matched pattern. If multiple ones are registered, all of the extras are ignored since the first match is the only one that will be used.
Also, because the view itself requires the `entity_id` to look up the `ProtectApiClient`, it will _always_ 404 if no entries are loaded since it cannot find the `ProtectApiClient`, again wasteful, but not harmful.
=> Removes extra const. Refactors service setup

CHANGELOG.md, custom_components/unifiprotect/sensor.py
* Changes `ble_signal` sensor to be available for any device that has a BLE connection (Sense is still the only one with it)
* Adds `phy_rate` sensor for wired devices
* Adds `wifi_signal` for WiFi devices
All connection state sensors are disabled by default.
=> Adds connection state sensors for all devices

CHANGELOG.md, custom_components/unifiprotect/manifest.json, custom_components/unifiprotect/select.py, custom_components/unifiprotect/sensor.py, custom_components/unifiprotect/switch.py
* Bumps pyunifiprotect to 1.3.0
* Adds `ufp_set_function` for switch entities
* Replaces various unit_of_measures with constants from HA
* `NEW`: Adds Paired Camera select entity for Viewports
* `NEW`: Adds "Received Data", "Transferred Data", "Oldest Recording", "Storage Used", and "Disk Write Rate" sensors for cameras. Disabled by default. Requires "Realtime metrics" option to update in realtime.
* `NEW`: (requires UniFi Protect 1.20.1) Adds "Voltage" sensor for doorbells. Disabled by default.
* `NEW`: Adds "System Sounds" switch for cameras with speakers
* `NEW`: Adds switches to toggle overlay information for video feeds on all cameras
* `NEW`: Adds switches to toggle smart detection types on cameras with smart detections
=> Adds various new entities

custom_components/unifiprotect/binary_sensor.py, custom_components/unifiprotect/sensor.py
* Reset `event_thumbnail` attribute for Motion binary sensor after motion has ended
* Change unit for signal strength from `db` to`dbm`. (fixes #394)
=> Bugfixes from 0.11-beta3

CHANGELOG.md, custom_components/unifiprotect/__init__.py, custom_components/unifiprotect/config_flow.py, custom_components/unifiprotect/const.py, custom_components/unifiprotect/manifest.json, custom_components/unifiprotect/select.py, custom_components/unifiprotect/services.yaml, custom_components/unifiprotect/strings.json, custom_components/unifiprotect/translations/en.json
* `NEW`: Adds `unifiprotect.set_doorbell_message` service. This is just like the `unifiprotect.set_doorbell_lcd_message`, but it is not deprecated and it requires the Doorbell Text Select entity instead of the Camera entity. Should **only** be used to set dynamic doorbell text messages (i.e. setting the current outdoor temperate on your doorbell). If you want to use static custom messages, use the Doorbell Text Select entity and the `unifiprotect.add_doorbell_text` / `unifiprotect.remove_doorbell_text` service. `unifiprotect.set_doorbell_lcd_message` is still deprecated and will still be removed in the next release.
* Closes #396
* `NEW`: Adds "Override Connection Host" config option. This will force your RTSP(S) connection IP address to be the same as everything else. Should only be used …
=> Adds CONF_OVERRIDE_CHOST and new dynamic doorbell service

CHANGELOG.md, custom_components/unifiprotect/binary_sensor.py, custom_components/unifiprotect/data.py, custom_components/unifiprotect/manifest.json, custom_components/unifiprotect/sensor.py
* `FIX`: Unadopted entities are ignored (fixes #420)
* `FIX`: Event thumbnails now return instantly using newer endpoint from UniFi Protect. They appear to come back as a camera snapshot until after the events ends, but they should always return an image now.
=> Updates to pyufp to 1.4.0 and remove e- from thumbnail URLs

.github/workflows/ci.yaml, README.md, custom_components/unifiprotect/entity.py, custom_components/unifiprotect/services.py
Now that the first HA core PR has been merged and `unifiprotect` will officially be in 2022.2, I figured it is a good idea to add this warning for users. I will go through and add it to all of the recent releases/tags (probably back to 0.9.x versions) as well so hopefully no one will miss the noticed.
=> Adds 2022.2 upgrade warning

.devcontainer/Dockerfile, CHANGELOG.md, custom_components/unifiprotect/button.py, custom_components/unifiprotect/camera.py, custom_components/unifiprotect/config_flow.py, custom_components/unifiprotect/const.py, custom_components/unifiprotect/data.py, custom_components/unifiprotect/entity.py, custom_components/unifiprotect/manifest.json, custom_components/unifiprotect/media_player.py
There are no new code changes in this PR. Just copy/pastes from the HA core version. Not everything was ported due to risk bugs with the changes to the base entity class. Will likely make another PR after everything else is ported. Just wanted to get some of the major fixes here in. 
Backports fixes from Home Assistant core merge process:
* `FIX`: Improves relibility of entities when UniFi Protect goes offline and/or a device goes offline. Everything recovery seemlessly when UniFi Protect upgrades or firmware updates are applied (fixes https://github.com/briis/unifiprotect/issues/432).
* `FIX`: Improves relibility of `media_player` entities so they should report state better and be able to play longer audio clips.
* `FIX`: Fixes stopping in progress audio for `media_player` entities.
* …
=> Backports various fixes from core merge

custom_components/unifiprotect/__init__.py, custom_components/unifiprotect/const.py, custom_components/unifiprotect/services.py, custom_components/unifiprotect/services.yaml, custom_components/unifiprotect/utils.py
One last debug service to add. It was originally only a utility for generating data for tests, but it can be something we integrate into issue reporting
There is actually a bug in the anonymization of data, so right now only "actual" works. I would also like to make it so the log messages actually log instead of print to console if not ran in "CLI mode", but both things are upstream in the in `pyunifiprotect` so does not affect this PR or any code in it.
=> Adds generate_data service
